# Generated by Django 3.2 on 2021-04-09 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteiras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('datahora', models.DateTimeField()),
                ('quantidade_parcelas', models.IntegerField(default=1)),
                ('encerrado', models.BooleanField(default=False)),
                ('situacao', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='ABERTO', max_length=20)),
            ],
            options={
                'ordering': ['-datahora'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('categorias', models.ManyToManyField(blank=True, to='lancamentos.Categoria')),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='carteiras.porta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('datahora', models.DateTimeField()),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receita', to='lancamentos.lancamento')),
            ],
            options={
                'ordering': ['-datahora'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('situacao', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='ABERTO', max_length=20)),
                ('despesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='lancamentos.despesa')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.AddField(
            model_name='despesa',
            name='lancamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despesa', to='lancamentos.lancamento'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug'], name='lancamentos_slug_1e2e80_idx'),
        ),
    ]
