# Generated by Django 3.2 on 2021-04-15 00:35

from django.db import migrations


def carga_categorias(apps, schema_editor):
    Categoria = apps.get_model('lancamentos', 'Categoria')
    Categoria.objects.get_or_create(titulo="Alimentação", slug="alimentacao", descricao="Gastos com alimentação.")
    Categoria.objects.get_or_create(titulo="Mercado", slug="mercado", descricao="Gastos com mercado.")
    Categoria.objects.get_or_create(titulo="Presente", slug="presente", descricao="Gastos com presente.")
    Categoria.objects.get_or_create(titulo="Serviços", slug="servicos", descricao="Gastos com serviços.")
    Categoria.objects.get_or_create(titulo="Salario", slug="salario", descricao="Salario recebido.")


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(carga_categorias),
    ]
