# Generated by Django 3.2 on 2021-04-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_auto_20210414_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Em Aberto'), (2, 'Pago'), (3, 'Cancelado'), (4, 'Estornado')], default=1),
        ),
    ]
