# Generated by Django 3.2 on 2021-04-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_auto_20210414_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='lancamentos.despesa'),
        ),
    ]
