# Generated by Django 3.2 on 2021-04-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_alter_despesa_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')]),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Em Aberto'), (2, 'Pago'), (3, 'Cancelado'), (4, 'Estornado')], default=1),
        ),
    ]
