# Generated by Django 3.2 on 2021-04-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0002_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='centro_custo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='carteiras.centrocusto'),
        ),
    ]
