# Generated by Django 3.1.7 on 2021-03-31 22:31

from django.db import migrations, models
import django.db.models.deletion


def incluir_tipos(apps, schema):

    Tipo = apps.get_model('carteiras', 'Tipo')

    tipo = Tipo(
        titulo='Conta Bancaria',
        slug='conta-bancaria',
        permite_parcelamento=False
    )
    tipo.save()

    tipo = Tipo(
        titulo='Carteira',
        slug='carteira',
        permite_parcelamento=False
    )
    tipo.save()

    tipo = Tipo(
        titulo='Cartao de Credito',
        slug='cartao-credito',
        permite_parcelamento=True
    )
    tipo.save()

    tipo = Tipo(
        titulo='Cartao de Beneficio',
        slug='cartao-beneficio',
        permite_parcelamento=False
    )
    tipo.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('permite_parcelamento', models.BooleanField()),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteiras.tipo')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.RunPython(incluir_tipos)
    ]
