# Generated by Django 3.2 on 2021-04-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteiras', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='pessoas.pessoa'),
        ),
        migrations.AddIndex(
            model_name='carteira',
            index=models.Index(fields=['slug'], name='carteiras_c_slug_2a6a9f_idx'),
        ),
    ]
