# Generated by Django 3.2 on 2021-04-10 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteiras', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='pessoas.pessoa'),
        ),
        migrations.AddIndex(
            model_name='carteira',
            index=models.Index(fields=['pessoa_id', 'slug'], name='carteiras_c_pessoa__e9d65e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carteira',
            unique_together={('pessoa_id', 'slug')},
        ),
    ]
