# Generated by Django 3.2 on 2021-04-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Conta'), (2, 'Cartão')]),
        ),
    ]
