# Generated by Django 3.2 on 2021-05-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
