# Generated by Django 3.1.7 on 2021-03-31 22:31

from django.db import migrations, models
import django.db.models.deletion


def incluir_categorias(apps, schema):

    Categoria = apps.get_model('lancamentos', 'Categoria')

    categoria = Categoria(
        titulo='Presente',
        slug='presente',
        descricao=''
    )
    categoria.save()

    categoria = Categoria(
        titulo='Mercado',
        slug='mercado',
        descricao=''
    )
    categoria.save()

    categoria = Categoria(
        titulo='Alimentação',
        slug='alimentacao',
        descricao=''
    )
    categoria.save()

    categoria = Categoria(
        titulo='Serviços',
        slug='servicos',
        descricao=''
    )
    categoria.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteiras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('datahora', models.DateTimeField()),
                ('parcelado', models.IntegerField(default=1)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteiras.carteira')),
                ('categorias', models.ManyToManyField(blank=True, to='lancamentos.Categoria')),
            ],
            options={
                'ordering': ['-datahora'],
            },
        ),
        migrations.RunPython(incluir_categorias)
    ]
